### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by AdamYLiang** [edherm/SpringBoard#1]
- [x] Make `Project Home View` earlier. Perhaps right after `Todos` 

Let me know if you have questions or want to talk about the change!

**Comment by edherm** [comment]
Thanks, Adam. I've shifted the project home view to begin after the to-do lists. I've changed my due-dates and timeline accordingly.

**Comment by AdamYLiang** [comment]
- [ ] Flip MVP 3 with 4, do project homepage first.
