### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by AdamYLiang** [edherm/SpringBoard#3]
**Projects**
- [x] No need to worry about `subscribers` right now since it is not a part of main MVPs. I would keep track of who the `lead` of the project is if you want to have someone attached to the project. 

**Todos**
- [x] Instead of `todo_items`, have `todos` be their own slice of state that just holds a `body` and reference to the `todo_list`. 

Let me know if you have any questions or want to talk about these changes!

**Comment by edherm** [comment]
Thanks, Adam. Just to clarify, do you think I should cut down the todo slice to just hold a reference to the `body` and `todo_list_id`? This seems like a significant difference in function from BaseCamp to remove the additional fields of `notes`, `event association`,  etc. 

I'm a little adrift on how to keep track of each different section's comments. My thought was that I would give each `commentable` slice access to associated `comment_ids`, but is there a better way to do this?

I've cut out all references to `subscribers` and `boosts` and I have added in a `session` slice (though I still have to fill that in.. :| )

**Comment by AdamYLiang** [comment]
I think in the meantime we should have our `todos` state only contain vital information related to the MVP. If you finish your MVPs then we can go back and add the remaining fields to the state. I wouldn't worry about all the features of Basecamp just yet, for now we can just have the basic functionality of making a todo and having it associated with the project. 

As for comments, this can also be more fleshed out after your main MVPs. For comments though, they can either be separate comment categories or send up the appropriate comment type in the jbuilder. So the end result is you will have all comments, regardless of what kind, in a comments slice of state and each comment will know what id/resource they have. 

And nice work on that! For the session slice of state it will just be the user logged in which you'll have a better idea on how to do after today! Let me know if this makes sense.
