### ISSUE TITLE
Frontend Routes 

### ISSUE THREAD

**Issue by AdamYLiang** [edherm/SpringBoard#4]
- [x] `Projects`, `Todo_lists`, and the remaining routes under should be properly nested to emulate the original app. For example, projects could be underneath `/:user_id/projects/:project_id` since we care about users as well as the project ID. Some of the routes on the original app are a bit obscured so you can nest them how you see appropriate. 

Let me know if you have any have any questions about the change.

**Comment by edherm** [comment]
I have updated these routes. I have tentatively decided to nest everything under their project ID because that makes sense to me. Hopefully the outline makes visual sense.
