### ISSUE TITLE
User Auth MVP

### ISSUE THREAD

**Issue by AdamYLiang** [edherm/SpringBoard#8]
Looks good! Here are some changes: 

**Functionality**
- [x] Nav bar should not appear during `Signup`/`Login` forms. Perhaps make those separate routes on the top level App. So you would have `Login`, `Signup`, and `MainApp`. 

**CSS**
- [x] Larger styling on splash page and login forms. Use the inspector to see how big elements should be. Specifically buttons such as `Log in` and `Try it FREE`. 
- [x] Remove `How it works`, `Before & after`, etc. in the nav bar since we will not have those links. 
- [x] Style `DemoUser` like how the Google auth button looks like on original app
- [x] Session Form should be further down on the page and logo should be at the top. Buttons/input should be slightly larger. 

I'd recommend putting your app and the original app side by side and seeing what looks off! Let me know if you have any questions about these changes.

**Comment by edherm** [comment]
I have removed the extraneous nav bar links, increased the login and try it free buttons, increased the font-size of the splash page header, shifted the session form down the page, and added the logo to that.

I am still working on:
- my Auth/Protected Routes
- onFocus/Blur to change the class of my input labels so that they shrink and stay shrunk.

I'll update you again when I've finished these and have pushed them to Heroku.

**Comment by edherm** [comment]
Hello, Adam!

Fixed: 
- auth/protected routes are working
- I completely redid the CSS for:
    - login
    - signup
    - splash
    - main navbar

Some of the css that I started with was way too vague and I was having to fight it later in my styling.. I still need to

Still needs work:
- onFocus/Blur for the session form only works in one direction (shrinking the label when i select an input) and it doesn't work with my demo user button
- my log in button on the session form is resisting my attempts to set it's size... 
- my signup yellow button is also resisting the urge to increase in size...
- the main navbar should be sticky
- the main navbar home button in the center

I am pushing these changes to heroku and will continue to work on the second bullet-list in the morning.

**Comment by edherm** [comment]
I also noticed the text color remains the same on the navbar after logging in... I'll fix that in the AM as well.

**Comment by edherm** [comment]
Hello Adam,

I have pushed my updates to heroku!

Immediately upon doing that, I noticed that I need to change my splash page text's line-spacing.

I also still need to make the nav bar sticky.

-Ed

**Comment by edherm** [comment]
Adam!

I have pushed my updates to heroku, again!

This time I have made the nav bar sticky and fixed my splash page's line-height.

My auth inputs are not done. I am stuck on the floating labels...

**Comment by AdamYLiang** [comment]
Gotcha, I'm taking a looking at the auth inputs right now and it seems a bit hard to click on the input fields. I assume thats due to the transition animation? I think what we have right now looks pretty solid though. If you want to move on from the floating labels/animations then you can! Even without the placeholders floating, the session form looks good.
