### ISSUE TITLE
Projects MVP 

### ISSUE THREAD

**Issue by AdamYLiang** [edherm/SpringBoard#9]
Looks good! Here are some changes: 

**Functionality**
- [x] Scroll window to top of the page when user clicks `Create Project` 
- [x] Render errors for project creation
- [x] Add ability to delete project. For now you can put it in the edit form if you don't have the sliding menu from clicking `...` 

**CSS**
- [x] Create page inputs should be slightly wider to match original app. 
- [x] `Add another project` should be centered and slightly larger to match original app. 

Let me know if you have any questions about these changes!

**Comment by edherm** [comment]
Hello, Adam! I believe I have fixed these issues! I noticed that the input box borders are the wrong color on heroku despite them looking correct on my localhost. Do you know if I need to change the format that I pick colors in my css to make those persist?

Other than that, these have all been completed.

**Comment by AdamYLiang** [comment]
Looks good! And are we talking about the blue border when we click on an input field? If so it looks good on my end so it's fine. Are you picking the color with hex values/RGB? If so that shouldn't influence heroku vs local.
